name: build
on:
  push:
    tags:
      - v*
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        check-latest: true

    - name: Install Go tip
      run: |
        curl -sL https://storage.googleapis.com/go-build-snap/go/linux-amd64/$(git ls-remote https://github.com/golang/go.git HEAD | awk '{print $1;}').tar.gz -o gotip.tar.gz
        ls -lah gotip.tar.gz
        mkdir -p $HOME/gotip
        tar -C $HOME/gotip -xzf gotip.tar.gz
    - run: make wasirun
    - run: make test GO=$HOME/gotip/bin/go
